#This compose file adds Heimdall Application Dashboard https://heimdall.site/ to your stack
version: '3.5'
services:
  reverse-proxy:
    networks: 
      - heimdall
  mail-relay:
    networks:
      - heimdall
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - heimdall-config:/config
    environment:
      APP_NAME: "My Apps"
      APP_URL: "https://welcometo.yourDynamicDomain.duckdns.org"
      FORCE_HTTPS: "true"
      MAIL_HOST: "mail-relay"
      MAIL_PORT: "25"
      #not used with mail-relay, but can be used
      MAIL_USERNAME: "null"
      MAIL_PASSWORD: "null"
      MAIL_ENCRYPTION: "null"
      TZ: "America/New_York"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=heimdall"
      - "traefik.frontend.rule=Host:welcometo.yourDynamicDomain.duckdns.org"
      - "traefik.docker.network=heimdall"
      - "traefik.default.protocol=http"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - heimdall
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://heimdall || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  heimdall:
    name: heimdall

volumes:
  heimdall-config:


