#This compose file adds ProjectSend Application Dashboard https://www.projectsend.org/ to your stack
version: '3.5'
services:
  reverse-proxy:
    networks:
      - projectsend
  projectsend:
    image: linuxserver/projectsend:latest
    container_name: projectsend
    volumes:
      - projectsend-config:/config
      - projectsend-data:/data
    environment:
      - MAX_UPLOAD=8000 #MB default: 5000
      - TZ=America/New_York #change this if you need to
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=projectsend"
      - "traefik.frontend.rule=Host:send.yourDynamicDomain.duckdns.org"
      - "traefik.docker.network=projectsend"
      - "traefik.default.protocol=http"
      - com.centurylinklabs.watchtower.enable="true"
    networks:
      - projectsend
    restart: unless-stopped
    depends_on:
      - projectsend-db
  projectsend-db:
    image: mariadb:latest
    container_name: projectsend-db
    #after starting project send, go to send.yourDynamicDomain.duckdns.org/install/make-config.php
    #to configure projectsend with the database info you provide here. The database host will be
    #"projectsend-db", type will be mySQL, make sure to change the System URI (second page) to start 
    #with https:// or else the page will be bare and the site will not work
    environment:
      - MYSQL_DATABASE=projectsend
      - MYSQL_USER=projectsend
      - MYSQL_PASSWORD=aSecureDBPassw0rd
      - MYSQL_ROOT_PASSWORD=aSecureDBRootPassw0rd
    volumes:
      - projectsend-database:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - com.centurylinklabs.watchtower.enable="true"
    restart: unless-stopped
    networks:
      - projectsend

networks:
  projectsend:
    name: projectsend

volumes:
  projectsend-config:
  projectsend-data:
  projectsend-database:
