#This compose file adds BookStack https://www.bookstackapp.com to your stack
version: '3.5'
services:
  reverse-proxy:
    networks: 
      - bookstack
  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    environment:
      - DB_DATABASE=bookstack
      - DB_USER=bookstack
      - DB_PASSWORD="YourSecureDBPassw0rd"
      - DB_HOST=bookstack-db
    volumes:
      - "bookstack-storage:/var/www/bookstack/public/storage"
      - "bookstack-uploads:/var/www/bookstack/public/uploads"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=bookstack"
      - "traefik.frontend.rule=Host:bookstack.yourDynamicDomain.duckdns.org"
      - "traefik.docker.network=bookstack"
      - "traefik.default.protocol=http"
      - com.centurylinklabs.watchtower.enable="true"
    networks:
      - bookstack
    restart: unless-stopped
    depends_on:
      - bookstack-db
  bookstack-db:
    image: mariadb:latest
    container_name: bookstack-db
    environment:
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD="yourSecureDBPassw0rd"
      - MYSQL_ROOT_PASSWORD="yourSecureDBR00tPass"
    volumes:
      - "bookstack-database-data:/var/lib/mysql"
    labels:
      - "traefik.enable=false"
      - com.centurylinklabs.watchtower.enable="true"
    restart: unless-stopped
    networks:
      - bookstack

networks:
  bookstack:
    name: bookstack

volumes:
  bookstack-storage:
  bookstack-uploads:
  bookstack-database-data:


