#This compose file adds Airsonic https://airsonic.github.io/ to your stack
version: '3.5'
services:
  reverse-proxy:
    networks:
      - airsonic
  airsonic:
    image: airsonic/airsonic
    container_name: airsonic
    volumes:
      - "~/Music:/airsonic/music:z"
      - "~/Podcasts:/airsonic/podcasts:z"
      - "~/.Playlists:/airsonic/playlists:z"
      - "airsonic-data:/airsonic/data"
    labels:
      - traefik.enable=true
      - traefik.port=4040
      - traefik.backend=airsonic
      - traefik.frontend.rule=Host:${AIRSONIC_DOMAIN:?Please copy template.env to .env and provide provide a value for AIRSONIC_DOMAIN}
      - traefik.docker.network=airsonic
      - traefik.default.protocol=http
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - airsonic
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://airsonic:4040 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  airsonic:
    name: airsonic

volumes:
  airsonic-data:
